In [260]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
sys.path.insert(0, '../utils')
import utils

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer

In [261]:
# Import csv to df
df = pd.read_csv('../data/renttherunway_cleaned_data.csv')

In [262]:
print(df.dtypes)

fit                object
user_id             int64
bust size          object
item_id             int64
weight            float64
rating            float64
rented for         object
review_text        object
body type          object
review_summary     object
category           object
height            float64
size                int64
age               float64
review_date        object
review_length       int64
band_size         float64
cup_size           object
dtype: object


In [263]:
# def logistic_regression_model(data):
#     # Label Encoding for categorical variables
#     label_encoders = {}
#     categorical_cols = ['bust size', 'rented for', 'body type', 'category', 'cup_size']
#     for col in categorical_cols:
#         le = LabelEncoder()
#         data[col] = le.fit_transform(data[col].astype(str))
#         label_encoders[col] = le

#     # Feature columns (excluding text and target columns)
#     feature_cols = [col for col in data.columns if col not in ['fit', 'review_text', 'review_summary', 'review_date']]

#     # Impute missing values
#     imputer = SimpleImputer(strategy='mean')
#     data[feature_cols] = imputer.fit_transform(data[feature_cols])

#     # Splitting the dataset
#     X = data[feature_cols]  # feature_cols defined in previous code
#     y = data['fit'].apply(lambda x: 1 if x == 'fit' else 0)
#     X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#     # Scaling features
#     scaler = StandardScaler()
#     X_train = scaler.fit_transform(X_train)
#     X_test = scaler.transform(X_test)

#     # Logistic Regression Model
#     model = LogisticRegression()

#     # Hyperparameter Grid
#     param_grid = {
#         'C': [0.001, 0.01, 0.1, 1, 10, 100],
#         'penalty': ['l1', 'l2'],
#         'solver': ['liblinear']
#     }

#     # Grid Search with Cross-Validation
#     grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy')
#     grid_search.fit(X_train, y_train)

#     best_model = grid_search.best_estimator_
#     print(f"Best parameters: {grid_search.best_params_}")
#     print(f"Best cross-validation score: {grid_search.best_score_}")

#     # Evaluate on test set
#     test_score = best_model.score(X_test, y_test)
#     print(f"Test set score: {test_score}")

#     return best_model



In [264]:
# model = logistic_regression_model(df)

In [265]:
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline

In [266]:
# def logistic_regression_model(data):
#     # Label Encoding for categorical variables
#     label_encoders = {}
#     categorical_cols = ['bust size', 'rented for', 'body type', 'category', 'cup_size', 'fit']
#     for col in categorical_cols:
#         le = LabelEncoder()
#         data[col] = le.fit_transform(data[col].astype(str))
#         label_encoders[col] = le

#     # Feature columns (excluding text and target columns)
#     feature_cols = [col for col in data.columns if col not in ['review_text', 'review_summary', 'review_date']]

#     # Impute missing values
#     imputer = SimpleImputer(strategy='mean')
#     data[feature_cols] = imputer.fit_transform(data[feature_cols])

#     data = data.dropna(subset=['rating'])

#     # Splitting the dataset
#     X = data[feature_cols]  # feature_cols defined in previous code
#     def map_rating_to_label(rating):
#         rating_mapping = {2.0: 0, 4.0: 1, 6.0: 2, 8.0: 3, 10.0: 4}
#         return rating_mapping.get(rating, 5)  # 5 is the label for 'others'

#     y = data['rating'].apply(map_rating_to_label)
    
#     X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#     # Scaling features
#     scaler = StandardScaler()
#     X_train = scaler.fit_transform(X_train)
#     X_test = scaler.transform(X_test)

#     # Logistic Regression Model
#     model = LogisticRegression()

#     # Hyperparameter Grid
#     param_grid = {
#         'C': [0.001, 0.01, 0.1, 1, 10, 100],
#         'penalty': ['l1', 'l2'],
#         'solver': ['liblinear']
#     }

#     # Grid Search with Cross-Validation
#     grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy')
#     grid_search.fit(X_train, y_train)

#     best_model = grid_search.best_estimator_
#     print(f"Best parameters: {grid_search.best_params_}")
#     print(f"Best cross-validation score: {grid_search.best_score_}")

#     # Evaluate on test set
#     test_score = best_model.score(X_test, y_test)
#     print(f"Test set score: {test_score}")

#     return best_model


In [267]:
# logistic_regression_model(df)

In [268]:
# GridSearchCV for Ratings prediction

In [269]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split, GridSearchCV
import numpy as np
import pandas as pd
from sklearn.metrics import f1_score, roc_auc_score, confusion_matrix, precision_score, recall_score
from sklearn.utils.class_weight import compute_class_weight

def logistic_regression_model(data):
    # Label Encoding for categorical variables
    label_encoders = {}
    categorical_cols = ['bust size', 'rented for', 'body type', 'category', 'cup_size', 'fit']
    for col in categorical_cols:
        le = LabelEncoder()
        data[col] = le.fit_transform(data[col].astype(str))
        label_encoders[col] = le

    # Feature columns (excluding text and target columns)
    # feature_cols = ['rented for', 'body type', 'category', 'height', 'size', 'age', 'review_length', 'band_size','cup_size', 'fit']
    feature_cols = ['fit', 'user_id', 'bust size', 'item_id', 'weight', 'rented for', 'body type', 'category', 'height', 'size', 'age', 'review_length', 'band_size', 'cup_size']
    # feature_cols = [col for col in data.columns if col not in ['review_text', 'review_summary', 'review_date']]
    # print(feature_cols)

    # Impute missing values
    imputer = SimpleImputer(strategy='mean')
    data[feature_cols] = imputer.fit_transform(data[feature_cols])

    data = data.dropna(subset=['rating'])

    # Splitting the dataset
    X = data[feature_cols]
    def map_rating_to_label(rating):
        rating_mapping = {2.0: 0, 4.0: 1, 6.0: 2, 8.0: 3, 10.0: 4}
        return rating_mapping.get(rating, 5)  # 5 is the label for 'others'

    y = data['rating'].apply(map_rating_to_label)
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    # Scaling features
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # Logistic Regression Model
    # model = LogisticRegression()
    model = LogisticRegression()


    # Hyperparameter Grid
    # param_grid = {
    #     'C': [0.001, 0.01, 0.1, 1, 10, 100],
    #     'penalty': ['l1', 'l2'],
    #     'solver': ['liblinear']
    # }
    param_grid = {
        # 'C': [10],
        # 'penalty': ['l1'],
        # 'solver': ['liblinear'],
        'C': [0.01, 0.1, 1, 10, 100],  # Regularization strength
        'penalty': ['l1', 'l2'],  # Penalty types
        'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],  # Solvers
        'class_weight': [
            {0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1},  # Equal weights
            {0: 2, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1},  # Higher weight for class 0
            {0: 1, 1: 2, 2: 1, 3: 1, 4: 1, 5: 1},  # Higher weight for class 1
            {0: 1, 1: 1, 2: 2, 3: 1, 4: 1, 5: 1},  # Higher weight for class 2
            {0: 1, 1: 1, 2: 1, 3: 2, 4: 1, 5: 1},  # Higher weight for class 3
            {0: 1, 1: 1, 2: 1, 3: 1, 4: 2, 5: 1},  # Higher weight for class 4
            {0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 2},  # Higher weight for class 5
            {0: 3, 1: 2, 2: 1, 3: 1, 4: 1, 5: 1},  # Custom weights as an example
            'balanced'  # Automatically compute weights based on class frequencies
        ]
    }

    # Grid Search with Cross-Validation
    grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy', verbose=1)
    grid_search.fit(X_train, y_train)

    best_model = grid_search.best_estimator_
    print(f"Best parameters: {grid_search.best_params_}")
    print(f"Best cross-validation score: {grid_search.best_score_}")

    # Evaluate on test set
    test_score = best_model.score(X_test, y_test)
    print(f"Accuracy: {test_score}")

    # Print MSE and BER
    y_pred = best_model.predict(X_test)
    print(f"MSE: {np.mean((y_test - y_pred)**2)}")
    print(f"BER: {1 - test_score}")

    # F1, AUC ROC, and Confusion Matrix, precision, recall
    print(f"F1 Score: {f1_score(y_test, y_pred, average='weighted')}")
    # print(f"AUC ROC: {roc_auc_score(y_test, y_pred, multi_class='ovr', average='weighted')}")
    print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}")
    print(f"Precision: {precision_score(y_test, y_pred, average='weighted')}")
    print(f"Recall: {recall_score(y_test, y_pred, average='weighted')}")
    print(f"Accuracy: {accuracy_score(y_test, y_pred)}")

    # Feature Importance Analysis
    # Get coefficients and calculate odds ratios
    coefficients = best_model.coef_[0]
    odds_ratios = np.exp(coefficients)

    # Create a DataFrame to display feature names and their corresponding odds ratios
    feature_importance = pd.DataFrame()
    feature_importance['feature'] = feature_cols
    feature_importance['odds_ratio'] = odds_ratios

    # Sort by odds_ratio to identify the most impactful feature
    most_impactful_feature = feature_importance.sort_values(by='odds_ratio', ascending=False)
    print("\nMost Impactful Features (based on odds ratios):")
    print(most_impactful_feature)

    return best_model

In [270]:
best_model = logistic_regression_model(df)

Fitting 2 folds for each of 4 candidates, totalling 8 fits
Best parameters: {'C': 10, 'class_weight': {0: 1, 1: 1, 2: 1, 3: 2, 4: 2, 5: 2}, 'penalty': 'l1', 'solver': 'liblinear'}
Best cross-validation score: 0.6466304876547403
Accuracy: 0.642442716361558
MSE: 0.7049308093316475
BER: 0.35755728363844197
F1 Score: 0.5321629006228377
Confusion Matrix: 
[[    0     0     0    43   292]
 [    0     0     0    77   774]
 [    0     0     0   248  2970]
 [    0     0     0   956 15163]
 [    0     0     0  1078 36138]]
Precision: 0.5320392355135318
Recall: 0.642442716361558
Accuracy: 0.642442716361558

Most Impactful Features (based on odds ratios):
          feature  odds_ratio
0             fit    2.146001
10            age    1.144901
7        category    1.098028
2       bust size    1.074440
1         user_id    1.072619
12      band_size    1.041507
4          weight    1.004582
9            size    0.980962
6       body type    0.970104
13       cup_size    0.964263
8          height 

c:\Users\mcgin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
